version: "3.9"

services:

  backend:
    build: .
    # image: backend
    ports:
      - "3000:3000"
    environment:
      TZ: "Europe/Moscow"
    command: npm run start:dev
    volumes:
      - .:/wallet

  pg:
    image: 'postgres:15.1-alpine'
    environment:
      POSTGRES_DB: 'wallet'
      POSTGRES_USER: 'wallet'
      POSTGRES_PASSWORD: 'example'
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
